{% set name = "qtwebengine" %}
{% set version = "6.9.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: 99cb0792abc2e39b299d73d8e2aa076b9ebcd55c3f4a4b5fd514eef5a62d03ab
    folder: {{ name }}
    patches:
      - patches/0001-gn-add-conda-paths.patch
      - patches/0002-add-system-lib-options-to-cmake-files.patch
      - patches/0003-allow-building-with-non-apple-clang-version.patch     # [osx]
      - patches/0004-chromium-force-settings-to-build-without-xcode.patch  # [osx]
      - patches/0005-set-rpath-on-generators-on-osx.patch                  # [osx]
      - patches/0006-disable-newer-glibc-features.patch                    # [linux and aarch64]
      - patches/0008-chromium-fix-readelf-path.patch                       # [linux]
      - patches/0009-fix-chromium-header.patch                             # [linux]
      - patches/0011-use-binary-input-for-gperf-on-Windows.patch           # [win]
      - patches/0013-disable-screencapturekit-on-osx.patch                 # [osx]

build:
  number: 1
  # https://doc.qt.io/qt-6/qt-releases.html#binary-compatibility
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  ignore_run_exports_from:
    # Vendored protobuf is bundled in the Chromium build so no need to require a conda package for it.
    # Remove this once we upgrade to Qt 6.10.
    - libprotobuf                                  # [linux]
    # These packages are only needed at build time
    - qttools
    - qtwebsockets
    - libglx-devel                                 # [linux]
    - glib
  missing_dso_whitelist:
    - "*/api-ms-win-core-realtime-l1-1-1.dll"      # [win]
    - "*/api-ms-win-core-winrt-string-l1-1-0.dll"  # [win]
    - "*/api-ms-win-core-winrt-l1-1-0.dll"         # [win]
    - "*/api-ms-win-power-base-l1-1-0.dll"         # [win]
    - "*/api-ms-win-shcore-scaling-l1-1-1.dll"     # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison          # [linux]
    - flex           # [linux]
    - gperf          # [linux]
    - jom            # [win]
    - msys2-bison    # [win]
    - msys2-flex     # [win]
    - msys2-gperf    # [win]
    - pkg-config     # [unix]
    - libtool        # [unix]
    - cmake
    - html5lib
    - ninja
    - nodejs
    - perl
  host:
    ### Qt Deps ###
    - qtbase-devel {{ version }}
    - qtdeclarative {{ version }}
    - qtwebchannel {{ version }}
    - qtwebsockets {{ version }}
    # Qt tools Designer is required to compile designer plugin.
    - qttools {{ version }}

    ### Linux Deps ###
    # ALSA audio library (needed for QT_FEATURE_webengine_system_alsa=ON)
    - alsa-lib {{ alsa_lib }}                      # [linux]
    - dbus {{ dbus }}                              # [linux]
    - expat {{ expat }}                            # [linux]
    # Qt6 requires at least 2.10.92 for access to FCConfigGetSysRoot()
    # https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcconfiggetsysroot.html
    - fontconfig {{ fontconfig }}                  # [linux]
    - gtk2 2.24.33                                 # [linux]
    - lcms2 {{ lcms2 }}                            # [linux]
    # CUPS library (needed for QT_FEATURE_webengine_printing_and_pdf=ON)
    - libcups 2.4                                  # [linux]
    - libdrm {{ libdrm }}                          # [linux]
    - libgl-devel {{ libgl }}                      # [linux]
    - libglx-devel {{ libglx }}                    # [linux]
    # Must build with same major version of protoc as Chromium (currently 3.20.3, so needs to be <4) or else generated
    # messages error out on include. Ideally, we only provide the vendored protoc to build with but mysql keeps pulling
    # it into the host env so we need to pin it.
    - libprotobuf 3.20.3                           # [linux]
    # X11/XCB dependencies needed by QtWebEngine/Chromium
    - libxcb {{ libxcb }}                          # [linux]
    - libxkbcommon {{ libxkbcommon }}              # [linux]
    - libxkbfile {{ libxkbfile }}                  # [linux]
    # mesalib provides libgbm.
    - mesalib {{ mesalib }}                        # [linux]
    - nspr {{ nspr }}                              # [linux]
    - nss {{ nss }}                                # [linux]
    - xorg-libx11 {{ xorg_libx11 }}                # [linux]
    - xorg-libxcomposite {{ xorg_libxcomposite }}  # [linux]
    - xorg-libxdamage {{ xorg_libxdamage }}        # [linux]
    - xorg-libxext {{ xorg_libxext }}              # [linux]
    - xorg-libxfixes {{ xorg_libxfixes }}          # [linux]
    - xorg-libxrandr {{ xorg_libxrandr }}          # [linux]
    - xorg-libxtst {{ xorg_libxtst }}              # [linux]

    ### Other Deps ###
    - freetype {{ freetype }}            # [unix]
    - glib {{ glib }}
    # Needs to be in hosts to allow QtPdf to build but is really a build dependency so no need to add to runtime deps.
    - html5lib 1.1
    - harfbuzz {{ harfbuzz }}
    - lcms2 {{ lcms2 }}
    - libevent {{ libevent }}
    - libtiff {{ libtiff }}
    - libopus {{ libopus }}              # [unix]
    - libvpx {{ libvpx }}                # [unix]
    - libvulkan-headers {{ libvulkan }}  # [not osx]
    - libvulkan-loader {{ libvulkan }}   # [not osx]
    - libwebp-base {{ libwebp_base }}
    - libxml2 {{ libxml2 }}
    - libxslt {{ libxslt }}
    # jpeg for QtWebEngine, openjpeg for QtPdf.
    - openjpeg {{ openjpeg }}
    - re2 {{ re2 }}
    - snappy {{ snappy }}

test:
  requires:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - make                              # [unix]
    - pkg-config                        # [unix]
    - qtbase-devel
  files:
    - test/main-qtwebengine.cpp
    - test/qml.qrc
    - test/qrc_qml.cpp
    - test/main.qml
    - test/qtwebengine.pro
  # The test commands are in run_test.sh and run_test.bat

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_file: {{ name }}/LICENSES/LGPL-3.0-only.txt
  license_family: LGPL
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}

extra:
  skip-lints:
    - has_run_test_and_commands
    - invalid_url
    - missing_source
    - missing_hash
